### PR TITLE
Adds an experimental simple grid layout

### PR DESCRIPTION
**Pull request by lneves12**
Issue: #247

Adds an experimental simple grid layout under an option "--grid". This assumes a grid of 2 columns, should be enough for now.

Let me know what you think about this approach. 

Example with even number of cells

Screenshot from 2020-11-05 01-47-18

Example with odd number of cells

Screenshot from 2020-11-05 01-47-03

### CODE REVIEW

**Comment by amertak** [comment]
I would love to see this feature released @lneves12

**Comment by nicholas-ochoa** [comment]
Any chance of this getting merged? This would be a very useful feature when there are multiple applications running that are in a `watch` mode and outputting multiple lines at once.

**Comment by paescuj** [comment]
Hey @lneves12, I'm sorry that you have not received any feedback for such a long time!
Thank you very much for your contribution! ❤️

The screenshots you've provided look awesome 💯

Nevertheless, I'm afraid we cannot include this in its current state for various reasons (besides the obvious required updates):
- In general, it seems to be to much in an "experimental state"
- [neo-blessed](https://github.com/embarklabs/neo-blessed) seems to be unmaintained - I'd like to avoid such dependencies
  (We'd need to look for an alternative, perhaps [terminal-kit](https://github.com/cronvel/terminal-kit)?)
- More tests needs to be added
- ...

That being said, this is not a general "no" to such a feature and I'd be pleased if you or someone else would like to continue working on this!

**Comment by paescuj** [comment]
Closing for now for the above reasons and because the pull request is outdated. Thanks anyway! ❤️ A new approach is welcome.

**Pull request closed without merging**
