### PR TITLE
Upgrade to pnpm 8

### PR DESCRIPTION
**Pull request by paescuj**

### CODE REVIEW

**Comment by paescuj** [comment]
Postponed to EOL of Node.js 14 (2023-04-30)

**Comment by danny007in** [comment]
i think better to use only official npm

**Comment by paescuj** [comment]
> better to use only latest npm is there any special use of pnpm

What do you mean exactly?

**Comment by danny007in** [comment]
> mean exactly?

Better to replace pnpm to latest npm

**Comment by gustavohenke** [comment]
Hey @danny007in, why do you think so?

**Comment by danny007in** [comment]
> Hey @danny007in, why do you think so?

Exactly that is my point, using stable npm package best option it also  links files from the global store.

**Comment by paescuj** [comment]
> [...] it also links files from the global store.

Did I miss something here? I'm not aware of this. Could you share a link?

Besides that, I don't think we're going back to `npm` (at least for now).
It has been shown that `pnpm` works very well for here. In particular, it has helped to greatly reduce the duration of the tests.

**Comment by danny007in** [comment]
> > [...] it also links files from the global store.
> 
> Did I miss something here? I'm not aware of this. Could you share a link?
> 
> Besides that, I don't think we're going back to `npm` (at least for now). It has been shown that `pnpm` works very well here. In particular, it has helped to greatly reduce the duration of the tests.

`npm v9` works as pnpm now.

https://stackoverflow.com/questions/74569635/npm-9-doesnt-copy-js-files-for-local-dependencies

**Review by gustavohenke — COMMENTED** [review]
@paescuj did you not want to proceed with this?

**Pull request closed without merging**
